Repository wecode-bootcamp-korea/fullstack1-2nd-OKYA-frontend, pull requests merged in 2021-08, with the labels that each got.

#7 [김민성] : 로그인 애니메이션, 벨리데이션 기능 구현
  package-lock.json
  package.json
  public/index.html
  src/Routes.jsx
  src/pages/Login/IdInput.jsx
  src/pages/Login/KakaoButton.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/PwInput.jsx
Labels: Status: 리뷰 요청

#9 [최민기] cart page 필요 레이아웃(애니메이션 구현 전)
  package-lock.json
  src/Routes.jsx
  src/pages/Cart/Cart.jsx
  src/pages/Cart/CartContainer.jsx
  src/pages/Cart/Coupon.jsx
  src/pages/Cart/EmptyCart.jsx
  src/pages/Cart/OrderContainer.jsx
  src/pages/Cart/OrderDetail.jsx
  src/pages/Main/MasonryImageWrap.jsx
  src/styles/theme.jsx
Labels: Status: 리뷰 요청

#10 [김민성] Axios method 추가
  package-lock.json
  src/pages/Login/KakaoButton.jsx
Labels: Status: 리뷰 요청

#11 [최민기] 장바구니 구현 중
  package-lock.json
  package.json
  public/data/CartData.json
  src/pages/Cart/Cart.jsx
  src/pages/Cart/CartContainer.jsx
  src/pages/Cart/CartItem.jsx
  src/pages/Cart/OrderContainer.jsx
  src/pages/Cart/OrderDetail.jsx
Labels: Status: Accepted

#12 [김민성] Nav 레이아웃 구현 완료
  package-lock.json
  package.json
  src/Routes.jsx
  src/components/Container/Container.jsx
  src/components/Nav/Icons.jsx
  src/components/Nav/Modal.jsx
  src/components/Nav/ModalLower1.jsx
  src/components/Nav/ModalLower2.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/NavLogo.jsx
  src/components/Nav/NavMenu.jsx
  src/components/Nav/SearchInput.jsx
  src/components/Nav/SideMenuButton.jsx
  src/pages/Login/WhiteLogo.jsx
  src/pages/Main/Main.jsx
  src/styles/theme.jsx
Labels: Status: 리뷰 진행중

#8 [오송미] 리스트 페이지 레이아웃 구현완료
  package-lock.json
  public/data/ListProductData.json
  public/data/productCategoryData.json
  src/pages/List/List.jsx
  src/pages/List/ListCategoryBar.jsx
  src/pages/List/ListProduct.jsx
  src/pages/List/ListProductCard.jsx
  src/pages/List/ListProductExplain.jsx
  src/pages/List/ListProductExplainImage.jsx
Labels: Status: 수정 요청, Status: Accepted

#6 [최민기] Masonry 레이아웃, 필터링, 페이지네이션(더보기) 구현 후 추가 레이아웃 진행 중
  public/data/categoryBtnData.json
  public/data/mainMasonryImageData.json
  public/data/mainPromotionData.json
  src/pages/Main/CategoryBtn.jsx
  src/pages/Main/IdeaCategories.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/MainBanner.jsx
  src/pages/Main/MainPromotion.jsx
  src/pages/Main/MasonryImages.jsx
  src/pages/Main/MasonryWrap.jsx
Labels: Status: 리뷰 진행중

#15 [김민성] 회원가입 기능 구현
  package.json
  src/components/Nav/Modal.jsx
  src/components/Nav/ModalLower1.jsx
  src/components/Nav/ModalLower2.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/SearchInput.jsx
  src/components/Nav/imageSearchModal.jsx
  src/pages/Login/KakaoButton.jsx
  src/pages/Login/SignUpButton.jsx
  src/pages/Signup/LeftSection.jsx
  src/pages/Signup/RightSection.jsx
  src/pages/Signup/Signup.jsx
Labels: Status: 리뷰 진행중

#14 [김민성] 이미지 업로드 검색기능 구현
  src/components/Nav/Modal.jsx
  src/components/Nav/ModalLower1.jsx
  src/components/Nav/ModalLower2.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/NavMenu.jsx
  src/components/Nav/SearchInput.jsx
  src/components/Nav/SideMenuButton.jsx
  src/components/Nav/imageSearchModal.jsx
  src/pages/Login/KakaoButton.jsx
Labels: Status: 리뷰 진행중

#18 [김민성 ]Footer 추가
  package.json
  src/components/Footer/Footer.jsx
  src/components/Nav/ImageSearchModal.jsx
  src/pages/Signup/RightSection.jsx
Labels: Status: 리뷰 요청

#17 [오송미] List 페이지 필터링 기능 추가
  package.json
  public/data/listProductData.json
  src/components/Nav/Nav.jsx
  src/pages/List/ListCategoryBar.jsx
  src/pages/List/ListProduct.jsx
  src/pages/List/ListProductCard.jsx
Labels: Status: 리뷰 요청

#13 [최민기] 장바구니 GET, PATCH, DELETE 메소드 구현 중
  .eslintrc.json
  public/data/CartData.json
  public/index.html
  src/config.js
  src/pages/Cart/Cart.jsx
  src/pages/Cart/CartContainer.jsx
  src/pages/Cart/CartItem.jsx
  src/pages/Cart/CartItems.jsx
  src/pages/Cart/CartWrap.jsx
  src/pages/Cart/Coupon.jsx
  src/pages/Cart/EmptyCart.jsx
  src/pages/Cart/OrderContainer.jsx
  src/pages/Cart/OrderDetail.jsx
Labels: Status: 수정 요청, Status: Conflict 해결 요청
