Repository wecode-bootcamp-korea/fullstack1-2nd-OKYA-frontend, pull requests merged in 2021-07, with the labels that each got.

#1 [김민성] Theme 수정
  package-lock.json
  src/Routes.js
  src/Routes.jsx
  src/components/Footer/Footer.jsx
  src/components/Nav/Nav.jsx
  src/index.jsx
  src/pages/Cart/Cart.jsx
  src/pages/List/List.js
  src/pages/List/List.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/LoginDescription.jsx
  src/pages/Main/Main.jsx
  src/pages/Signup/Signup.jsx
  src/styles/GlobalStyles.jsx
  src/styles/mixins.jsx
  src/styles/theme.js
  src/styles/theme.jsx
Labels: Status: 추가 기능 구현중

#4 [오송미] List 컴포넌트 코드 작성 완료, ListProduct 컴포넌트 코드 추가 작성 중
  public/data/ListProductData.json
  src/pages/List/List.jsx
  src/pages/List/ListProduct.jsx
  src/pages/Login/Login.jsx
  src/styles/theme.jsx
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#5 [최민기] container 컴포넌트 생성
  src/components/Container/Container.jsx
  src/components/Footer/Footer.jsx
  src/styles/theme.jsx
Labels: Status: 리뷰 요청
